const videos = {
  "Módulo 1" : [
    { "name": "Aula 1 - Objetivo do Curso Back to Work!", "id": "T5mzxYpp3WQ" },
    { "name": "Aula 2 - Carreira com Propósito", "id": "IVsVdM0c3dU" },
    { "name": "Aula 3 - Contratações em tempo de recessão", "id": "PVquyBzVno4" },
    { "name": "Aula 4 - O profissional do futuro", "id": "2zRnJlG6FEM" },
    { "name": "Aula 5 - Característica x Benefício", "id": "ZzqiUtWpzlk" },
    { "name": "Aula 6 - O Papel do Dinheiro", "id": "UVjNjoKyGeE" },
    { "name": "Aula 7 - O Papel do Networking", "id": "MUdiCHePcdw" },
    { "name": "Aula 8 - Linkedin x Curriculum Vitae", "id": "eDRCDOFL8g4" },
    { "name": "Aula 9 - Aprofundamento no Linkedin", "id": "6kiU92cO3ps" },
    { "name": "Aula 10 - Storytelling e sua Carreira", "id": "7y70JPVVHqc" },
    { "name": "Aula 11 - Linkedin - Construindo um perfil campeão: O básico", "id": "O9yEQegk38g" },
    { "name": "Aula 12 - Linkedin - Construindo um perfil campeão: Eu e os outros", "id": "S0HJDgztXJ8" },
    { "name": "Aula 13 - Linkedin - Construindo um perfil campeão: Engajamento", "id": "1KcB7B6Wteg" },
    { "name": "Aula 14 - Linkedin - Construindo um perfil campeão: Publicações e Artigos", "id": "QwnngXfAAv4" },
    { "name": "Aula 15 - O que não fazer no Linkedin?", "id": "FhKNqaWXEkU" },
    { "name": "Aula 16 - Estudando a empresa", "id": "XB4btXfx9E4" },
    { "name": "Aula 17 - Estudando o Mercado", "id": "0Vu_lQW0sug" },
    { "name": "Aula 18 - Estudando os Founders e CEO", "id": "VBp0hiCI0ao" },
    { "name": "Aula 19 - Estudando os valores da empresa", "id": "tOUTnHlh1ZY" },
    { "name": "Aula 20 - Estudando a job (competências)", "id": "SFVN27VhaA8" },
    { "name": "Aula 21 - O que o RH costuma olhar no Linkedin de um candidato?", "id": "j8KOqbZadlE" },
    { "name": "Aula 22 - Um currículo ou Linkedin deve mudar dependendo da vaga/empresa?", "id": "2WrH3a5Z9cM" },
    { "name": "Aula 23 - Por que o RH não deu retorno sobre a minha aplicação?", "id": "4M2L7HYhrGU" },
    { "name": "Aula 24 - Um currículo ou Linkedin deve mudar dependendo da vaga/empresa?", "id": "4RrsFeKMrlA" },
    { "name": "Aula 25 - O que é Live Screening? Como me sair bem?", "id": "Y9OgbBo3EiU" },
    { "name": "Aula 26 - Para que serve a entrevista com o RH? Como devo me preparar?", "id": "LslkhVxIBTE" },
    { "name": "Aula 27 - Na entrevista comportamental, como diferenciar competência de qualidade?", "id": "WNdnRvK9P84" },
    { "name": "Aula 28 - O que existe por trás do “Gostamos do seu perfil, mas no momento não seguiremos”?", "id": "xSepHRnu0_Q" },
    { "name": "Aula 29 - O processo seletivo está demorando. Devo entrar em contato?", "id": "ZBgDOCUnn1I" },
    { "name": "Aula 30 - Processo seletivo: Teste Inicial", "id": "5bNmrER67PY" },
    { "name": "Aula 31 - Processo seletivo: Entrevista com RH", "id": "_5WvAJbPHtU" },
    { "name": "Aula 32 - Processo seletivo: Entrevista com Coordenador ou pares", "id": "55uIcQVA1v0&t"},
    { "name": "Aula 33 - Processo seletivo: Entrevista com Diretor", "id": "YEuRXzIWkJU" },
    { "name": "Aula 34 - Processo seletivo: Simulação da Job", "id": "Jt1nuZB7Dmg" },
    { "name": "Aula 35 - O que aprendi entrevistando mais de 300 talentos?", "id": "i_D2SG_d-hk" },
    { "name": "Aula 36 - A pergunta de ouro", "id": "Pt1KNjbWWz0" },
    { "name": "Aula 37 (Aula Final) - Bibliografia + Livros recomendados", "id": "bH5zAiiN4rY" }
  ],
  "Módulo 2" : [
    { "name": "Gorillaz - Dirty Harry", "id": "cLnkQAeMbIM"},
    { "name": "Megh Stock - Vestido de Festa", "id": "4PDMjlsmFTo"},
    { "name": "Ana Tijoux - Sacar la Voz", "id": "VAayt5BsEWg"},
    { "name": "Tom Misch - Disco Yes", "id": "EXWOJvlDwbU"},
    { "name": "Molotov - Frijolero", "id": "H0YSd6lMxRk"}
  ],
  "Módulo 3" : [
    { "name": "Ana Tijoux - Antipatriarca", "id": "RoKoj8bFg2E"},
    { "name": "Tim Maia - Me Dê Motivo", "id": "6UtOV_KNnjk"},
    { "name": "Pink Floyd - Another Brick in The Wall - 100% real não fake", "id": "LqrZtvDbcts?start=35"},
    { "name": "Dummy Video 1", "id": "6iFbuIpe68k"},
    { "name": "Dummy Video 2", "id": "B-N1yJyrQRY"},
    { "name": "Dummy Video 3", "id": "EEvopkbc4FE?start=67"}
  ]
}
